export const cityOptionsMap = {
  Australia: [
    { label: { en: "Melbourne", zh: "墨尔本" }, value: "Melbourne" },
    { label: { en: "Sydney", zh: "悉尼" }, value: "Sydney" },
    { label: { en: "Brisbane", zh: "布里斯班" }, value: "Brisbane" },
    { label: { en: "Adelaide", zh: "阿德莱德" }, value: "Adelaide" },
    { label: { en: "Perth", zh: "珀斯" }, value: "Perth" },
    { label: { en: "Gold Coast", zh: "黄金海岸" }, value: "Gold Coast" },
    { label: { en: "Newcastle", zh: "纽卡斯尔" }, value: "Newcastle" },
    { label: { en: "Canberra", zh: "堪培拉" }, value: "Canberra" },
    { label: { en: "Wollongong", zh: "卧龙岗" }, value: "Wollongong" },
    { label: { en: "Hobart", zh: "霍巴特" }, value: "Hobart" },
    { label: { en: "Sunshine Coast", zh: "阳光海岸" }, value: "Sunshine Coast" },
    { label: { en: "Geelong", zh: "吉朗" }, value: "Geelong" },
    { label: { en: "Townsville", zh: "汤斯维尔" }, value: "Townsville" },
    { label: { en: "Cairns", zh: "凯恩斯" }, value: "Cairns" },
    { label: { en: "Toowoomba", zh: "图文巴" }, value: "Toowoomba" },
    { label: { en: "Ballarat", zh: "巴拉瑞特" }, value: "Ballarat" },
    { label: { en: "Bendigo", zh: "本迪戈" }, value: "Bendigo" },
    { label: { en: "Mackay", zh: "麦凯" }, value: "Mackay" },
    { label: { en: "Rockhampton", zh: "罗克汉普顿" }, value: "Rockhampton" },
    { label: { en: "Launceston", zh: "朗塞斯顿" }, value: "Launceston" },
    { label: { en: "Darwin", zh: "达尔文" }, value: "Darwin" },
    { label: { en: "Albury", zh: "奥尔伯里" }, value: "Albury" },
    { label: { en: "Coffs Harbour", zh: "科夫斯港" }, value: "Coffs Harbour" },
    { label: { en: "Wagga Wagga", zh: "瓦加瓦加" }, value: "Wagga Wagga" },
    { label: { en: "Shepparton", zh: "谢珀顿" }, value: "Shepparton" },
    { label: { en: "Bunbury", zh: "班伯里" }, value: "Bunbury" },
    { label: { en: "Bundaberg", zh: "班达伯格" }, value: "Bundaberg" },
    { label: { en: "Hervey Bay", zh: "赫维湾" }, value: "Hervey Bay" },
    { label: { en: "Mildura", zh: "米尔杜拉" }, value: "Mildura" },
    { label: { en: "Port Macquarie", zh: "麦夸里港" }, value: "Port Macquarie" },
    { label: { en: "Orange", zh: "奥兰治" }, value: "Orange" },
    { label: { en: "Dubbo", zh: "达博" }, value: "Dubbo" },
    { label: { en: "Bathurst", zh: "巴瑟斯特" }, value: "Bathurst" },
    { label: { en: "Warrnambool", zh: "沃南布尔" }, value: "Warrnambool" },
    { label: { en: "Nowra", zh: "瑙拉" }, value: "Nowra" },
    { label: { en: "Albany", zh: "奥尔巴尼" }, value: "Albany" },
    { label: { en: "Geraldton", zh: "杰拉尔顿" }, value: "Geraldton" },
    { label: { en: "Kalgoorlie", zh: "卡尔古利" }, value: "Kalgoorlie" },
    { label: { en: "Mount Gambier", zh: "甘比尔山" }, value: "Mount Gambier" },
    { label: { en: "Tamworth", zh: "塔姆沃思" }, value: "Tamworth" }
  ],
  China: [
    { label: { en: "Beijing", zh: "北京" }, value: "Beijing" },
    { label: { en: "Shanghai", zh: "上海" }, value: "Shanghai" },
    { label: { en: "Shenzhen", zh: "深圳" }, value: "Shenzhen" },
    { label: { en: "Guangzhou", zh: "广州" }, value: "Guangzhou" },
    { label: { en: "Chengdu", zh: "成都" }, value: "Chengdu" },
    { label: { en: "Hangzhou", zh: "杭州" }, value: "Hangzhou" },
    { label: { en: "Nanjing", zh: "南京" }, value: "Nanjing" },
    { label: { en: "Wuhan", zh: "武汉" }, value: "Wuhan" },
    { label: { en: "Xiamen", zh: "厦门" }, value: "Xiamen" },
    { label: { en: "Suzhou", zh: "苏州" }, value: "Suzhou" }
  ],
  "Hong Kong": [
    { label: { en: "Central", zh: "中环" }, value: "Central" },
    { label: { en: "Causeway Bay", zh: "铜锣湾" }, value: "Causeway Bay" },
    { label: { en: "Wan Chai", zh: "湾仔" }, value: "Wan Chai" },
    { label: { en: "Tsim Sha Tsui", zh: "尖沙咀" }, value: "Tsim Sha Tsui" },
    { label: { en: "Mong Kok", zh: "旺角" }, value: "Mong Kok" },
    { label: { en: "North Point", zh: "北角" }, value: "North Point" },
    { label: { en: "Quarry Bay", zh: "鲗鱼涌" }, value: "Quarry Bay" },
    { label: { en: "Kwun Tong", zh: "观塘" }, value: "Kwun Tong" },
    { label: { en: "Tai Po", zh: "大埔" }, value: "Tai Po" },
    { label: { en: "Tuen Mun", zh: "屯门" }, value: "Tuen Mun" }
  ],
  "Singapore": [
    { label: { en: "Central Region", zh: "中央区" }, value: "Central Region" },
    { label: { en: "Orchard", zh: "乌节路" }, value: "Orchard" },
    { label: { en: "Raffles Place", zh: "莱佛士坊" }, value: "Raffles Place" },
    { label: { en: "Marina Bay", zh: "滨海湾" }, value: "Marina Bay" },
    { label: { en: "Sentosa", zh: "圣淘沙" }, value: "Sentosa" },
    { label: { en: "Jurong East", zh: "裕廊东" }, value: "Jurong East" },
    { label: { en: "Tampines", zh: "淡滨尼" }, value: "Tampines" },
    { label: { en: "Woodlands", zh: "兀兰" }, value: "Woodlands" },
    { label: { en: "Sengkang", zh: "盛港" }, value: "Sengkang" },
    { label: { en: "Punggol", zh: "榜鹅" }, value: "Punggol" }
  ],
  "Taiwan": [
    { label: { en: "Taipei", zh: "台北" }, value: "Taipei" },
    { label: { en: "New Taipei", zh: "新北" }, value: "New Taipei" },
    { label: { en: "Taichung", zh: "台中" }, value: "Taichung" },
    { label: { en: "Kaohsiung", zh: "高雄" }, value: "Kaohsiung" },
    { label: { en: "Taoyuan", zh: "桃园" }, value: "Taoyuan" },
    { label: { en: "Tainan", zh: "台南" }, value: "Tainan" },
    { label: { en: "Hsinchu", zh: "新竹" }, value: "Hsinchu" },
    { label: { en: "Keelung", zh: "基隆" }, value: "Keelung" },
    { label: { en: "Chiayi", zh: "嘉义" }, value: "Chiayi" },
    { label: { en: "Hualien", zh: "花莲" }, value: "Hualien" }
  ],
  "United States": [
    { label: { en: "New York, NY", zh: "纽约, 纽约州" }, value: "New York" },
    { label: { en: "Los Angeles, CA", zh: "洛杉矶, 加利福尼亚州" }, value: "Los Angeles" },
    { label: { en: "Chicago, IL", zh: "芝加哥, 伊利诺伊州" }, value: "Chicago" },
    { label: { en: "Houston, TX", zh: "休斯顿, 得克萨斯州" }, value: "Houston" },
    { label: { en: "Phoenix, AZ", zh: "凤凰城, 亚利桑那州" }, value: "Phoenix" },
    { label: { en: "Philadelphia, PA", zh: "费城, 宾夕法尼亚州" }, value: "Philadelphia" },
    { label: { en: "San Antonio, TX", zh: "圣安东尼奥, 得克萨斯州" }, value: "San Antonio" },
    { label: { en: "San Diego, CA", zh: "圣地亚哥, 加利福尼亚州" }, value: "San Diego" },
    { label: { en: "Dallas, TX", zh: "达拉斯, 得克萨斯州" }, value: "Dallas" },
    { label: { en: "San Jose, CA", zh: "圣何塞, 加利福尼亚州" }, value: "San Jose" },
    { label: { en: "Austin, TX", zh: "奥斯汀, 得克萨斯州" }, value: "Austin" },
    { label: { en: "Jacksonville, FL", zh: "杰克逊维尔, 佛罗里达州" }, value: "Jacksonville" },
    { label: { en: "Fort Worth, TX", zh: "沃斯堡, 得克萨斯州" }, value: "Fort Worth" },
    { label: { en: "Columbus, OH", zh: "哥伦布, 俄亥俄州" }, value: "Columbus" },
    { label: { en: "San Francisco, CA", zh: "旧金山, 加利福尼亚州" }, value: "San Francisco" },
    { label: { en: "Charlotte, NC", zh: "夏洛特, 北卡罗来纳州" }, value: "Charlotte" },
    { label: { en: "Indianapolis, IN", zh: "印第安纳波利斯, 印第安纳州" }, value: "Indianapolis" },
    { label: { en: "Seattle, WA", zh: "西雅图, 华盛顿州" }, value: "Seattle" },
    { label: { en: "Denver, CO", zh: "丹佛, 科罗拉多州" }, value: "Denver" },
    { label: { en: "Washington, DC", zh: "华盛顿特区" }, value: "Washington DC" },
    { label: { en: "Boston, MA", zh: "波士顿, 马萨诸塞州" }, value: "Boston" },
    { label: { en: "El Paso, TX", zh: "埃尔帕索, 得克萨斯州" }, value: "El Paso" },
    { label: { en: "Nashville, TN", zh: "纳什维尔, 田纳西州" }, value: "Nashville" },
    { label: { en: "Detroit, MI", zh: "底特律, 密歇根州" }, value: "Detroit" },
    { label: { en: "Oklahoma City, OK", zh: "俄克拉荷马城, 俄克拉荷马州" }, value: "Oklahoma City" },
    { label: { en: "Portland, OR", zh: "波特兰, 俄勒冈州" }, value: "Portland" },
    { label: { en: "Las Vegas, NV", zh: "拉斯维加斯, 内华达州" }, value: "Las Vegas" },
    { label: { en: "Memphis, TN", zh: "孟菲斯, 田纳西州" }, value: "Memphis" },
    { label: { en: "Louisville, KY", zh: "路易斯维尔, 肯塔基州" }, value: "Louisville" },
    { label: { en: "Baltimore, MD", zh: "巴尔的摩, 马里兰州" }, value: "Baltimore" }
  ]
} as const;

export type CountryKey = keyof typeof cityOptionsMap; 